// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/csotherden/prescription-parser/ent/embedding"
	"github.com/csotherden/prescription-parser/ent/prescription"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// EmbeddingCreate is the builder for creating a Embedding entity.
type EmbeddingCreate struct {
	config
	mutation *EmbeddingMutation
	hooks    []Hook
}

// SetEmbedding sets the "embedding" field.
func (ec *EmbeddingCreate) SetEmbedding(pg pgvector.Vector) *EmbeddingCreate {
	ec.mutation.SetEmbedding(pg)
	return ec
}

// SetID sets the "id" field.
func (ec *EmbeddingCreate) SetID(u uuid.UUID) *EmbeddingCreate {
	ec.mutation.SetID(u)
	return ec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ec *EmbeddingCreate) SetNillableID(u *uuid.UUID) *EmbeddingCreate {
	if u != nil {
		ec.SetID(*u)
	}
	return ec
}

// SetPrescriptionID sets the "prescription" edge to the Prescription entity by ID.
func (ec *EmbeddingCreate) SetPrescriptionID(id uuid.UUID) *EmbeddingCreate {
	ec.mutation.SetPrescriptionID(id)
	return ec
}

// SetPrescription sets the "prescription" edge to the Prescription entity.
func (ec *EmbeddingCreate) SetPrescription(p *Prescription) *EmbeddingCreate {
	return ec.SetPrescriptionID(p.ID)
}

// Mutation returns the EmbeddingMutation object of the builder.
func (ec *EmbeddingCreate) Mutation() *EmbeddingMutation {
	return ec.mutation
}

// Save creates the Embedding in the database.
func (ec *EmbeddingCreate) Save(ctx context.Context) (*Embedding, error) {
	ec.defaults()
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EmbeddingCreate) SaveX(ctx context.Context) *Embedding {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EmbeddingCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EmbeddingCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EmbeddingCreate) defaults() {
	if _, ok := ec.mutation.ID(); !ok {
		v := embedding.DefaultID()
		ec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EmbeddingCreate) check() error {
	if _, ok := ec.mutation.Embedding(); !ok {
		return &ValidationError{Name: "embedding", err: errors.New(`ent: missing required field "Embedding.embedding"`)}
	}
	if len(ec.mutation.PrescriptionIDs()) == 0 {
		return &ValidationError{Name: "prescription", err: errors.New(`ent: missing required edge "Embedding.prescription"`)}
	}
	return nil
}

func (ec *EmbeddingCreate) sqlSave(ctx context.Context) (*Embedding, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EmbeddingCreate) createSpec() (*Embedding, *sqlgraph.CreateSpec) {
	var (
		_node = &Embedding{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(embedding.Table, sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeUUID))
	)
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ec.mutation.Embedding(); ok {
		_spec.SetField(embedding.FieldEmbedding, field.TypeOther, value)
		_node.Embedding = value
	}
	if nodes := ec.mutation.PrescriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   embedding.PrescriptionTable,
			Columns: []string{embedding.PrescriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.embedding_prescription = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmbeddingCreateBulk is the builder for creating many Embedding entities in bulk.
type EmbeddingCreateBulk struct {
	config
	err      error
	builders []*EmbeddingCreate
}

// Save creates the Embedding entities in the database.
func (ecb *EmbeddingCreateBulk) Save(ctx context.Context) ([]*Embedding, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Embedding, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmbeddingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EmbeddingCreateBulk) SaveX(ctx context.Context) []*Embedding {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EmbeddingCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EmbeddingCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
