// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/csotherden/prescription-parser/ent/embedding"
	"github.com/csotherden/prescription-parser/ent/prescription"
	"github.com/csotherden/prescription-parser/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	embeddingFields := schema.Embedding{}.Fields()
	_ = embeddingFields
	// embeddingDescID is the schema descriptor for id field.
	embeddingDescID := embeddingFields[0].Descriptor()
	// embedding.DefaultID holds the default value on creation for the id field.
	embedding.DefaultID = embeddingDescID.Default.(func() uuid.UUID)
	prescriptionMixin := schema.Prescription{}.Mixin()
	prescriptionMixinFields0 := prescriptionMixin[0].Fields()
	_ = prescriptionMixinFields0
	prescriptionFields := schema.Prescription{}.Fields()
	_ = prescriptionFields
	// prescriptionDescCreatedAt is the schema descriptor for created_at field.
	prescriptionDescCreatedAt := prescriptionMixinFields0[0].Descriptor()
	// prescription.DefaultCreatedAt holds the default value on creation for the created_at field.
	prescription.DefaultCreatedAt = prescriptionDescCreatedAt.Default.(func() time.Time)
	// prescriptionDescID is the schema descriptor for id field.
	prescriptionDescID := prescriptionFields[0].Descriptor()
	// prescription.DefaultID holds the default value on creation for the id field.
	prescription.DefaultID = prescriptionDescID.Default.(func() uuid.UUID)
}
