// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Embedding is the predicate function for embedding builders.
type Embedding func(*sql.Selector)

// Prescription is the predicate function for prescription builders.
type Prescription func(*sql.Selector)
